
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainplatform_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - trainplatform

  nginx:
    image: nginx:alpine
    container_name: trainplatform_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - trainplatform

  db:
    image: mysql:8.0
    container_name: trainplatform_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: entrenamientos
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - trainplatform

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: trainplatform_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - trainplatform

volumes:
  dbdata:

networks:
  trainplatform:
